trigger:
  tags:
    - refs/tags/*
  pr: none
  paths:
    exclude:
      - *.md
      - *.MD

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Run the build script from the repository.'
  env:
    NUGET_ORG_KEY: $(NUGET_KEY)
  inputs:
    targetType: 'inline'
    script: |
      cd src/base
      ./create_nuget
