# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Run the build script from the repository.'
  env:
    NUGET_ORG_KEY: $(NUGET_KEY)
  inputs:
    targetType: 'inline'
    script: |
      cd src/base
      ./create_nuget
