# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: nuget_deployment

steps:

- task: Bash@3
  displayName: 'Retrieve latest git tag.'
  inputs:
    targetType: 'inline'
    script: |
      echo $NUGET_KEY
      cd src/base
      ./create_nuget
