# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: 'src/base'

- script: dotnet test
  displayName: 'Run the unit tests.'
  workingDirectory: 'src/base'

- script: dotnet pack --output $(Build.BinariesDirectory)/nuget
  displayName: 'Create a new nuget package.'
  workingDirectory: 'src/base'

- script: echo $(Build.BinariesDirectory)
  displayName: 'debug thingy.'
  workingDirectory: 'src/base'


- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.BinariesDirectory)/nuget/*.nupkg;!$(Build.BinariesDirectory)/nuget/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget_Connection_EK'
    versioningScheme: 'off'