# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

-task: Bash@3
 displayName: 'Install dependencies'
 inputs:
   tragetType: 'inline'
   script: |
     sudo apt-get install -y tree

- task: Bash@3
  displayName: 'Retrieve latest git tag.'
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=GIT_TAG;]$(git describe --tags)"

- task: DotNetCoreCLI@2
  displayName: 'Clean solution.'
  inputs:
    command: 'custom'
    projects: 'src/base/Base.fsproj'
    custom: 'clean'

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies.'
  inputs:
    command: 'restore'
    projects: 'src/base/Base.fsproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build solution.'
  inputs:
    command: 'build'
    projects: 'src/base/Base.fsproj'
    arguments: '-c "Release"'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests.'
  inputs:
    command: 'test'
    projects: 'src/base/Base.fsproj'

- task: Bash@3
  displayName: 'Echo GIT_TAG.'
  inputs:
    targetType: 'inline'
    script: |
      echo $GIT_TAG
      tree

- task: DotNetCoreCLI@2
  displayName: 'Pack release binaries.'
  inputs:
    command: 'pack'
    packagesToPack: '$(BuildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GIT_TAG'

- task: NuGetCommand@2
  displayName: 'Push to nuget.'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: 'src/base/lib/Release/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget_Connection_EK'
    versioningScheme: 'off'