#!/usr/bin/env bash
echo "Deleting obj and bin folders."
rm -rf bin obj lib 		>>create_nuget.log 2>&1
set -e
echo "Cleaning project."
dotnet clean 			>> create_nuget.log 2>&1
echo "Restoring projects."
dotnet restore 			>> create_nuget.log 2>&1
echo "Building release."
dotnet build -c "Release" 	>> create_nuget.log 2>&1
echo "Running tests."
dotnet test 			>> create_nuget.log 2>&1
echo "Packing release."
dotnet pack -c "Release" 	>> create_nuget.log 2>&1
